/**
 * Report generation with markdown formatting
 */

import { Finding } from '../types';
import { writeFile } from '../utils/file-utils';
import { ReportOptions } from './index';
import { calculateCvssScore } from './severity-scorer';

/**
 * Generate a markdown report
 */
export async function generateMarkdownReport(
  findings: Finding[],
  options: ReportOptions
): Promise<string> {
  const markdown = generateMarkdown(findings);
  await writeFile(options.outputPath, markdown);
  return options.outputPath;
}

/**
 * Generate markdown content
 */
function generateMarkdown(findings: Finding[]): string {
  const timestamp = new Date().toISOString();

  let md = `# Smart Contract Security Report

**Generated:** ${timestamp}
**Findings:** ${findings.length}
**Tool:** Scout Security Scanner v1.0.0

---

## Executive Summary

This report contains the results of an automated security analysis performed on the target smart contracts. The analysis identified **${findings.length}** potential security issues across various severity levels.

### Severity Distribution

${generateSeverityTable(findings)}

${generateSeverityChart(findings)}

---

## Findings

`;

  // Sort findings by severity
  const sortedFindings = [...findings].sort((a, b) => {
    const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, informational: 4 };
    return severityOrder[a.severity] - severityOrder[b.severity];
  });

  sortedFindings.forEach((finding, index) => {
    md += generateFindingSection(finding, index + 1);
  });

  md += `
---

## Recommendations

### High Priority

${getHighPriorityRecommendations(findings)}

### General Best Practices

1. **Use Latest Solidity Version**: Upgrade to Solidity 0.8.0+ for built-in overflow protection
2. **Follow Checks-Effects-Interactions**: Always update state before external calls
3. **Implement Access Control**: Use OpenZeppelin's AccessControl or Ownable
4. **Add Reentrancy Guards**: Protect sensitive functions with ReentrancyGuard
5. **Validate All Inputs**: Never trust user-provided data
6. **Use SafeMath for Older Versions**: If using Solidity < 0.8.0
7. **Regular Security Audits**: Conduct professional audits before mainnet deployment
8. **Comprehensive Testing**: Achieve >90% test coverage
9. **Bug Bounty Programs**: Incentivize responsible disclosure
10. **Monitor Deployed Contracts**: Use tools like Tenderly or Forta

---

## Responsible Disclosure

If submitting to a bug bounty program:

1. **Review the program's policy** on their platform (HackerOne, Bugcrowd, etc.)
2. **Provide clear reproduction steps** and PoC code
3. **Include impact assessment** and potential exploit scenarios
4. **Suggest remediation** with code examples
5. **Respect the disclosure timeline** (typically 90 days)
6. **Do not exploit on mainnet** - use testnets or forks only

### Bug Bounty Submission Template

\`\`\`
Title: [Vulnerability Type] in [Contract Name]

Severity: [Critical/High/Medium/Low]

Description:
[Detailed explanation of the vulnerability]

Impact:
[What an attacker could achieve]

Reproduction Steps:
1. [Step-by-step guide]
2. [Include code snippets]
3. [Show expected vs actual behavior]

Proof of Concept:
[Link to PoC code or attach file]

Remediation:
[Suggested fix with code examples]

References:
[Links to relevant security resources]
\`\`\`

---

## Appendix

### About This Report

This report was generated using the Scout security scanner, an automated tool for smart contract vulnerability detection. While automated tools are valuable, they should be used in conjunction with manual code review and professional security audits.

**Limitations:**

- Automated scanners may produce false positives
- Complex logic bugs may not be detected
- Business logic vulnerabilities require manual review
- Results should be verified by security professionals

### References

- [Ethereum Smart Contract Best Practices](https://consensys.github.io/smart-contract-best-practices/)
- [SWC Registry](https://swcregistry.io/)
- [OpenZeppelin Contracts](https://docs.openzeppelin.com/contracts/)
- [Solidity Documentation](https://docs.soliditylang.org/)

---

*Report generated by Scout Security Scanner - https://github.com/scout-security*
`;

  return md;
}

/**
 * Generate severity distribution table
 */
function generateSeverityTable(findings: Finding[]): string {
  const distribution: Record<string, number> = {
    Critical: 0,
    High: 0,
    Medium: 0,
    Low: 0,
    Informational: 0,
  };

  findings.forEach(f => {
    const key = f.severity.charAt(0).toUpperCase() + f.severity.slice(1);
    distribution[key] = (distribution[key] || 0) + 1;
  });

  return `
| Severity | Count | Percentage |
|----------|-------|------------|
| 🔴 Critical | ${distribution.Critical} | ${getPercentage(distribution.Critical, findings.length)}% |
| 🟠 High | ${distribution.High} | ${getPercentage(distribution.High, findings.length)}% |
| 🟡 Medium | ${distribution.Medium} | ${getPercentage(distribution.Medium, findings.length)}% |
| 🔵 Low | ${distribution.Low} | ${getPercentage(distribution.Low, findings.length)}% |
| ⚪ Informational | ${distribution.Informational} | ${getPercentage(distribution.Informational, findings.length)}% |
| **Total** | **${findings.length}** | **100%** |
`;
}

/**
 * Generate ASCII severity chart
 */
function generateSeverityChart(findings: Finding[]): string {
  const distribution: Record<string, number> = {};
  findings.forEach(f => {
    distribution[f.severity] = (distribution[f.severity] || 0) + 1;
  });

  const chart: string[] = [];
  const maxCount = Math.max(...Object.values(distribution));

  ['critical', 'high', 'medium', 'low', 'informational'].forEach(severity => {
    const count = distribution[severity] || 0;
    const barLength = maxCount > 0 ? Math.round((count / maxCount) * 40) : 0;
    const bar = '█'.repeat(barLength);
    const emoji = { critical: '🔴', high: '🟠', medium: '🟡', low: '🔵', informational: '⚪' }[severity];
    chart.push(`${emoji} ${severity.padEnd(15)} ${bar} ${count}`);
  });

  return '```\n' + chart.join('\n') + '\n```';
}

/**
 * Generate individual finding section
 */
function generateFindingSection(finding: Finding, index: number): string {
  const severityEmoji = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    informational: '⚪',
  }[finding.severity];

  const cvssScore = calculateCvssScore(finding);

  let section = `
### ${index}. ${severityEmoji} ${finding.title}

**ID:** \`${finding.id}\`
**Rule:** \`${finding.rule_id}\`
**Severity:** ${finding.severity.toUpperCase()} (CVSS: ${cvssScore.toFixed(1)})
**Confidence:** ${finding.confidence}
**Contract:** ${finding.contract}

#### Description

${finding.description || 'No description provided'}

#### Location

`;

  finding.files.forEach(file => {
    section += `- **File:** \`${file.path}\`\n`;
    section += `- **Lines:** ${file.line_start}-${file.line_end}\n`;

    if (file.snippet) {
      section += `\n**Code Snippet:**\n\n\`\`\`solidity\n${file.snippet}\n\`\`\`\n`;
    }
  });

  section += `
#### Impact

${finding.impact}

**Likelihood:** ${finding.likelihood}

#### Recommendation

${finding.recommendation}

`;

  if (finding.poc) {
    section += `#### Proof of Concept

A proof of concept has been generated for this finding:

- **Type:** ${finding.poc.type}
- **Path:** \`${finding.poc.path}\`
- **Simulated:** ${finding.poc.simulated ? 'Yes (safe)' : 'No'}

`;

    if (finding.poc.steps && finding.poc.steps.length > 0) {
      section += '**Reproduction Steps:**\n\n';
      finding.poc.steps.forEach((step, i) => {
        section += `${i + 1}. ${step}\n`;
      });
      section += '\n';
    }
  }

  if (finding.references && finding.references.length > 0) {
    section += '#### References\n\n';
    finding.references.forEach(ref => {
      section += `- ${ref}\n`;
    });
    section += '\n';
  }

  if (finding.tags && finding.tags.length > 0) {
    section += `**Tags:** ${finding.tags.map(t => `\`${t}\``).join(', ')}\n`;
  }

  section += '\n---\n';

  return section;
}

/**
 * Get high priority recommendations
 */
function getHighPriorityRecommendations(findings: Finding[]): string {
  const highSeverity = findings.filter(f => ['critical', 'high'].includes(f.severity));

  if (highSeverity.length === 0) {
    return '- No critical or high severity issues found. Continue following security best practices.';
  }

  const recommendations = new Set<string>();
  highSeverity.forEach(f => {
    recommendations.add(f.recommendation);
  });

  return Array.from(recommendations)
    .slice(0, 5)
    .map((rec, i) => `${i + 1}. ${rec}`)
    .join('\n');
}

/**
 * Calculate percentage
 */
function getPercentage(count: number, total: number): string {
  if (total === 0) return '0.0';
  return ((count / total) * 100).toFixed(1);
}
